name: Test SNTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sntp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use sntp client
        run: |
          ip a
          ip route
          sudo apt install sntp
          sudo tcpdump -i any -nn -vvv udp &
          sleep 1
          sudo sntp -4 time.google.com || true
          sudo sntp -4 time.windows.com || true
          sleep 5 # wait for tcpdump output
