name: Test SNTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sntp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Start tcpdump
        run: sudo tcpdump -i any -nn port 123 &
      
      - name: Use sntp client
        run: |
          sudo apt install sntp
          sudo sntp time.google.com
          pgrep sntp
