name: Test SNTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sntp:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v3
      
      - name: Use sntp client
        run: |
          ip a
          ip route
          sudo apt install sntp
          sudo tcpdump -i any -nn -vvv udp &
          sleep 1
          sudo sntp -4 time.google.com || true
          sudo sntp -4 time.google.com || true
          sudo sntp -4 time.google.com || true
          sudo sntp -4 time.windows.com || true
          sleep 5 # wait for tcpdump output
          echo # flush output

  sntp-mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        n: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use sntp client
        run: |
          # sudo tcpdump -i any -nn -vvv udp &
          # sleep 1
          sntp -d time.google.com
          sntp -d time.google.com
          sntp -d time.google.com
          sntp -d time.google.com
          # sleep 5 # wait for tcpdump output
          # echo # flush output
