name: Test SNTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sntp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use sntp client
        run: |
          sudo tcpdump -i any -nn not port 443 &
          sudo apt install sntp
          sudo sntp -4 time.google.com || true
          pgrep tcpdump
